/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import src.Cliente;

/**
 *
 * @author Vini
 */
public class TelaCliente extends javax.swing.JFrame {
    private int userId = 0;
    private int idUserSelecionado;
    ArrayList<Cliente> clientes = new ArrayList<Cliente>();
    /**
     * Creates new form telaCliente
     */
    public TelaCliente() {
        initComponents();
        
        setLocationRelativeTo(null);
        
        this.btnSalvar.setEnabled(false);
        this.btnAlterar.setEnabled(false);
        this.btnExcluir.setEnabled(false);
    }
    
    private void UpdateTable() {
        DefaultTableModel model = (DefaultTableModel) this.jtblTable.getModel();
        
        for(int i = 0; i < model.getRowCount(); i++) {
            model.removeRow(i);
        }
        
        for(int i = 0; i < clientes.size(); i++) {
            Object[] row = new Object[5];
            
            row[0] = clientes.get(i).getId();
            row[1] = clientes.get(i).getRG();
            row[2] = clientes.get(i).getCPF();
            row[3] = clientes.get(i).getNome();
            row[4] = clientes.get(i).getTelefone();
            
            model.addRow(row);
        }
        
        this.jtblTable.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnlCadastro = new javax.swing.JPanel();
        txtfRg = new javax.swing.JTextField();
        txtfCpf = new javax.swing.JTextField();
        txtfNome = new javax.swing.JTextField();
        txtfTelefone = new javax.swing.JTextField();
        lblRg = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        jpnlButtons = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        txtfPesquisar = new javax.swing.JTextField();
        lblPesquisar = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JButton();
        jspTable = new javax.swing.JScrollPane();
        jtblTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cliente");
        setAlwaysOnTop(true);

        jpnlCadastro.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro"));

        txtfRg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfRgActionPerformed(evt);
            }
        });
        txtfRg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfRgKeyTyped(evt);
            }
        });

        txtfCpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfCpfKeyTyped(evt);
            }
        });

        txtfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfNomeActionPerformed(evt);
            }
        });
        txtfNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfNomeKeyTyped(evt);
            }
        });

        txtfTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfTelefoneActionPerformed(evt);
            }
        });
        txtfTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfTelefoneKeyTyped(evt);
            }
        });

        lblRg.setText("Rg:");

        lblCpf.setText("CPF:");

        lblNome.setText("Nome");

        lblTelefone.setText("Telefone:");

        javax.swing.GroupLayout jpnlCadastroLayout = new javax.swing.GroupLayout(jpnlCadastro);
        jpnlCadastro.setLayout(jpnlCadastroLayout);
        jpnlCadastroLayout.setHorizontalGroup(
            jpnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlCadastroLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jpnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtfRg, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRg)
                    .addComponent(lblCpf))
                .addGap(306, 306, 306)
                .addGroup(jpnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTelefone)
                    .addComponent(lblNome)
                    .addComponent(txtfNome)
                    .addComponent(txtfTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnlCadastroLayout.setVerticalGroup(
            jpnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlCadastroLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jpnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRg)
                    .addComponent(lblNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(jpnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpf)
                    .addComponent(lblTelefone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        txtfPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfPesquisarActionPerformed(evt);
            }
        });

        lblPesquisar.setText("Pesquisar por Rg:");

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnlButtonsLayout = new javax.swing.GroupLayout(jpnlButtons);
        jpnlButtons.setLayout(jpnlButtonsLayout);
        jpnlButtonsLayout.setHorizontalGroup(
            jpnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlButtonsLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelar)
                .addGap(18, 18, 18)
                .addComponent(btnAlterar)
                .addGap(18, 18, 18)
                .addComponent(btnExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(btnPesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtfPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPesquisar))
                .addGap(23, 23, 23))
        );
        jpnlButtonsLayout.setVerticalGroup(
            jpnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlButtonsLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jpnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnlButtonsLayout.createSequentialGroup()
                        .addGroup(jpnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpnlButtonsLayout.createSequentialGroup()
                                .addComponent(lblPesquisar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtfPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpnlButtonsLayout.createSequentialGroup()
                        .addGroup(jpnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSalvar)
                            .addComponent(btnCancelar)
                            .addComponent(btnAlterar)
                            .addComponent(btnExcluir))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jtblTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Rg", "CPF", "Nome", "Telefone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtblTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblTableMouseClicked(evt);
            }
        });
        jspTable.setViewportView(jtblTable);
        if (jtblTable.getColumnModel().getColumnCount() > 0) {
            jtblTable.getColumnModel().getColumn(0).setResizable(false);
            jtblTable.getColumnModel().getColumn(1).setResizable(false);
            jtblTable.getColumnModel().getColumn(2).setResizable(false);
            jtblTable.getColumnModel().getColumn(3).setResizable(false);
            jtblTable.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jspTable)
                    .addComponent(jpnlButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnlCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnlButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jspTable, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfNomeActionPerformed
      
    }//GEN-LAST:event_txtfNomeActionPerformed

    private void txtfTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfTelefoneActionPerformed
      
    }//GEN-LAST:event_txtfTelefoneActionPerformed

    private void txtfRgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfRgActionPerformed
       
    }//GEN-LAST:event_txtfRgActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        userId++;
        String nome = this.txtfNome.getText();
        String Cpf = this.txtfCpf.getText();
        String Rg = this.txtfRg.getText();
        String telefone = this.txtfTelefone.getText();
        
        Cliente cliente = new Cliente(userId, Rg, Cpf, nome, telefone);
        
        clientes.add(cliente);
        
        UpdateTable();
        
        this.txtfNome.setText("");
        this.txtfCpf.setText("");
        this.txtfRg.setText("");
        this.txtfTelefone.setText("");
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtfPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfPesquisarActionPerformed
       
    }//GEN-LAST:event_txtfPesquisarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void txtfRgKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfRgKeyTyped
        String nameInput = this.txtfNome.getText();
        String telefoneInput = this.txtfTelefone.getText();
        String rgInput = this.txtfRg.getText();
        String cpfInput = this.txtfCpf.getText();
        
        if(nameInput.length() > 0 && telefoneInput.length() > 0 && rgInput.length() > 0 && cpfInput.length() > 0 && !this.btnAlterar.isEnabled()) {
            this.btnSalvar.setEnabled(true);
        } else {
            this.btnSalvar.setEnabled(false);
        }
    }//GEN-LAST:event_txtfRgKeyTyped

    private void txtfCpfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfCpfKeyTyped
        String nameInput = this.txtfNome.getText();
        String telefoneInput = this.txtfTelefone.getText();
        String rgInput = this.txtfRg.getText();
        String cpfInput = this.txtfCpf.getText();
        
        if(nameInput.length() > 0 && telefoneInput.length() > 0 && rgInput.length() > 0 && cpfInput.length() > 0 && !this.btnAlterar.isEnabled()) {
            this.btnSalvar.setEnabled(true);
        } else {
            this.btnSalvar.setEnabled(false);
        }
    }//GEN-LAST:event_txtfCpfKeyTyped

    private void txtfNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfNomeKeyTyped
        String nameInput = this.txtfNome.getText();
        String telefoneInput = this.txtfTelefone.getText();
        String rgInput = this.txtfRg.getText();
        String cpfInput = this.txtfCpf.getText();
        
        if(nameInput.length() > 0 && telefoneInput.length() > 0 && rgInput.length() > 0 && cpfInput.length() > 0 && !this.btnAlterar.isEnabled()) {
            this.btnSalvar.setEnabled(true);
        } else {
            this.btnSalvar.setEnabled(false);
        }
    }//GEN-LAST:event_txtfNomeKeyTyped

    private void txtfTelefoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfTelefoneKeyTyped
        String nameInput = this.txtfNome.getText();
        String telefoneInput = this.txtfTelefone.getText();
        String rgInput = this.txtfRg.getText();
        String cpfInput = this.txtfCpf.getText();
        
        if(nameInput.length() > 0 && telefoneInput.length() > 0 && rgInput.length() > 0 && cpfInput.length() > 0 && !this.btnAlterar.isEnabled()) {
            this.btnSalvar.setEnabled(true);
        } else {
            this.btnSalvar.setEnabled(false);
        }
    }//GEN-LAST:event_txtfTelefoneKeyTyped

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.txtfNome.setText("");
        this.txtfCpf.setText("");
        this.txtfRg.setText("");
        this.txtfTelefone.setText("");
        this.btnSalvar.setEnabled(false);
        this.btnAlterar.setEnabled(false);
        this.btnExcluir.setEnabled(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jtblTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblTableMouseClicked
        int index = this.jtblTable.getSelectedRow();
        
        if(index < 0 || index >= clientes.size()) return;
        
        Cliente cliente = clientes.get(index);
        
        this.txtfCpf.setText(cliente.getCPF());
        this.txtfRg.setText(cliente.getRG());
        this.txtfNome.setText(cliente.getNome());
        this.txtfTelefone.setText(cliente.getTelefone());
        
        this.idUserSelecionado = index + 1;
        
        this.btnSalvar.setEnabled(false);
        this.btnAlterar.setEnabled(true);
        this.btnExcluir.setEnabled(true);
    }//GEN-LAST:event_jtblTableMouseClicked

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        String nameInput = this.txtfNome.getText();
        String telefoneInput = this.txtfTelefone.getText();
        String rgInput = this.txtfRg.getText();
        String cpfInput = this.txtfCpf.getText();
        
        Cliente cliente = clientes.get(this.idUserSelecionado - 1);
        
        cliente.setCPF(cpfInput);
        cliente.setNome(nameInput);
        cliente.setRG(rgInput);
        cliente.setTelefone(telefoneInput);
        
        this.UpdateTable();
        
        
        this.txtfNome.setText("");
        this.txtfCpf.setText("");
        this.txtfRg.setText("");
        this.txtfTelefone.setText("");
        
        this.btnAlterar.setEnabled(false);
        this.btnCancelar.setEnabled(true);
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        clientes.remove(this.idUserSelecionado - 1);
        
        this.txtfNome.setText("");
        this.txtfCpf.setText("");
        this.txtfRg.setText("");
        this.txtfTelefone.setText("");
        
        UpdateTable();
        
        this.btnAlterar.setEnabled(false);
        this.btnExcluir.setEnabled(false);
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JPanel jpnlButtons;
    private javax.swing.JPanel jpnlCadastro;
    private javax.swing.JScrollPane jspTable;
    private javax.swing.JTable jtblTable;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPesquisar;
    private javax.swing.JLabel lblRg;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JTextField txtfCpf;
    private javax.swing.JTextField txtfNome;
    private javax.swing.JTextField txtfPesquisar;
    private javax.swing.JTextField txtfRg;
    private javax.swing.JTextField txtfTelefone;
    // End of variables declaration//GEN-END:variables
}
