/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author Vini
 */
public class TelaChamado extends javax.swing.JFrame {

    /**
     * Creates new form telaCliente
     */
    public TelaChamado() {
        initComponents();
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnlCadastro = new javax.swing.JPanel();
        lblData = new javax.swing.JLabel();
        ftxtfData = new javax.swing.JFormattedTextField();
        lblTipo = new javax.swing.JLabel();
        txtfTipo = new javax.swing.JTextField();
        lblOrigem = new javax.swing.JLabel();
        txtfOrigem = new javax.swing.JTextField();
        lblDestino = new javax.swing.JLabel();
        txtfDestino = new javax.swing.JTextField();
        lblHorarioPartida = new javax.swing.JLabel();
        txtfHorarioPartida = new javax.swing.JTextField();
        lblHorarioRetorno = new javax.swing.JLabel();
        txtfHorarioRetorno = new javax.swing.JTextField();
        lblQuilometragemInicial = new javax.swing.JLabel();
        txtfQuilometragemInicial = new javax.swing.JTextField();
        lblQuilometragemFinal = new javax.swing.JLabel();
        txtfQuilometragemFinal = new javax.swing.JTextField();
        lblValorFinal = new javax.swing.JLabel();
        ftxtfValorTotal = new javax.swing.JFormattedTextField();
        jpnlButtons = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        txtfPesquisar = new javax.swing.JTextField();
        lblPesquisar = new javax.swing.JLabel();
        jspTable = new javax.swing.JScrollPane();
        jtblTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jpnlCadastro.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro"));

        lblData.setText("Data:");

        ftxtfData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        ftxtfData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftxtfDataActionPerformed(evt);
            }
        });

        lblTipo.setText("Tipo");

        lblOrigem.setText("Origem");

        txtfOrigem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfOrigemActionPerformed(evt);
            }
        });

        lblDestino.setText("Destino:");

        txtfDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfDestinoActionPerformed(evt);
            }
        });

        lblHorarioPartida.setText("Horario de partida:");

        txtfHorarioPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfHorarioPartidaActionPerformed(evt);
            }
        });

        lblHorarioRetorno.setText("Horario de retorno:");

        txtfHorarioRetorno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfHorarioRetornoActionPerformed(evt);
            }
        });

        lblQuilometragemInicial.setText("Quilometragem Inicial:");

        txtfQuilometragemInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfQuilometragemInicialActionPerformed(evt);
            }
        });

        lblQuilometragemFinal.setText("Quilometragem Final:");

        lblValorFinal.setText("Valor Total:");

        ftxtfValorTotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        javax.swing.GroupLayout jpnlCadastroLayout = new javax.swing.GroupLayout(jpnlCadastro);
        jpnlCadastro.setLayout(jpnlCadastroLayout);
        jpnlCadastroLayout.setHorizontalGroup(
            jpnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblData)
                    .addGroup(jpnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtfHorarioPartida, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtfTipo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblDestino, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtfDestino, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                .addComponent(lblHorarioPartida, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtfHorarioRetorno, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ftxtfData, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(lblHorarioRetorno)))
                    .addComponent(lblOrigem)
                    .addComponent(lblTipo)
                    .addComponent(txtfOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblQuilometragemInicial)
                    .addComponent(lblQuilometragemFinal)
                    .addComponent(lblValorFinal)
                    .addComponent(ftxtfValorTotal)
                    .addComponent(txtfQuilometragemInicial)
                    .addComponent(txtfQuilometragemFinal, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addGap(149, 149, 149))
        );
        jpnlCadastroLayout.setVerticalGroup(
            jpnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlCadastroLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jpnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuilometragemInicial)
                    .addComponent(lblData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftxtfData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfQuilometragemInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo)
                    .addComponent(lblQuilometragemFinal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfQuilometragemFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOrigem)
                    .addComponent(lblValorFinal, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxtfValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDestino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtfDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHorarioPartida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtfHorarioPartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHorarioRetorno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtfHorarioRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");

        btnAlterar.setText("Alterar");

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        txtfPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfPesquisarActionPerformed(evt);
            }
        });

        lblPesquisar.setText("Pesquisar pela Data:");

        javax.swing.GroupLayout jpnlButtonsLayout = new javax.swing.GroupLayout(jpnlButtons);
        jpnlButtons.setLayout(jpnlButtonsLayout);
        jpnlButtonsLayout.setHorizontalGroup(
            jpnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlButtonsLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelar)
                .addGap(18, 18, 18)
                .addComponent(btnAlterar)
                .addGap(36, 36, 36)
                .addComponent(btnPesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtfPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPesquisar))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        jpnlButtonsLayout.setVerticalGroup(
            jpnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlButtonsLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jpnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpnlButtonsLayout.createSequentialGroup()
                        .addGroup(jpnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSalvar)
                            .addComponent(btnCancelar)
                            .addComponent(btnAlterar)
                            .addComponent(lblPesquisar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtfPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtblTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Rg", "CPF", "Nome", "Telefone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jspTable.setViewportView(jtblTable);
        if (jtblTable.getColumnModel().getColumnCount() > 0) {
            jtblTable.getColumnModel().getColumn(0).setResizable(false);
            jtblTable.getColumnModel().getColumn(1).setResizable(false);
            jtblTable.getColumnModel().getColumn(2).setResizable(false);
            jtblTable.getColumnModel().getColumn(3).setResizable(false);
            jtblTable.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jspTable)
                    .addComponent(jpnlButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnlCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnlButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jspTable, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtfPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfPesquisarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void ftxtfDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftxtfDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftxtfDataActionPerformed

    private void txtfDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfDestinoActionPerformed

    private void txtfOrigemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfOrigemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfOrigemActionPerformed

    private void txtfHorarioRetornoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfHorarioRetornoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfHorarioRetornoActionPerformed

    private void txtfHorarioPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfHorarioPartidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfHorarioPartidaActionPerformed

    private void txtfQuilometragemInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfQuilometragemInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfQuilometragemInicialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaChamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaChamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaChamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaChamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaChamado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JFormattedTextField ftxtfData;
    private javax.swing.JFormattedTextField ftxtfValorTotal;
    private javax.swing.JPanel jpnlButtons;
    private javax.swing.JPanel jpnlCadastro;
    private javax.swing.JScrollPane jspTable;
    private javax.swing.JTable jtblTable;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblDestino;
    private javax.swing.JLabel lblHorarioPartida;
    private javax.swing.JLabel lblHorarioRetorno;
    private javax.swing.JLabel lblOrigem;
    private javax.swing.JLabel lblPesquisar;
    private javax.swing.JLabel lblQuilometragemFinal;
    private javax.swing.JLabel lblQuilometragemInicial;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblValorFinal;
    private javax.swing.JTextField txtfDestino;
    private javax.swing.JTextField txtfHorarioPartida;
    private javax.swing.JTextField txtfHorarioRetorno;
    private javax.swing.JTextField txtfOrigem;
    private javax.swing.JTextField txtfPesquisar;
    private javax.swing.JTextField txtfQuilometragemFinal;
    private javax.swing.JTextField txtfQuilometragemInicial;
    private javax.swing.JTextField txtfTipo;
    // End of variables declaration//GEN-END:variables
}
